# Generated by Django 4.2.14 on 2024-09-11 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdname', models.CharField(max_length=50)),
                ('stdclass', models.IntegerField()),
                ('stdadd', models.CharField(max_length=50)),
                ('sname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='app.school')),
            ],
        ),
    ]
